### ISSUE TITLE
missing vvc

### ISSUE THREAD

**Issue by initialneil** [malteprinzler/diner#1]
Thanks for the great work!

Running `create_prediction_folder.py` raises error when loading ckpt `assets\ckpts\dtu\DINER.ckpt`. Error on:
> self.nerf = import_obj(nerf_conf.module)(**nerf_conf.kwargs)
> self.renderer = import_obj(renderer_conf.module)(**renderer_conf.kwargs)

Both `vvc.models.pixelnerf.PixelNeRF` and `vvc.models.nerf_renderer.NeRFRenderer` are missing.

**Comment by malteprinzler** [comment]
Thank you very much for your interest in our work and for pointing out that bug. 

The problem was a deprecated naming convention in the provided checkpoints. Please find the updated assets.zip under the following link (same as given in the README.md): https://edmond.mpdl.mpg.de/dataset.xhtml?persistentId=doi:10.17617/3.NBIYQB#

If you have any further questions, I would be happy to help!
