### ISSUE TITLE
missing argument ‘mlp_coarse_conf’

### ISSUE THREAD

**Issue by scutcr7** [malteprinzler/diner#2]
hello, thanks for the great work!

Running create_prediction_folder.py raises error when loading ckpt `assets\ckpts\facescape\DINER.ckpt`. Error on:
```
self.nerf = import_obj(nerf_conf.module)(**nerf_conf.kwargs)
self.renderer = import_obj(renderer_conf.module)(**renderer_conf.kwargs)
```
![inference](https://github.com/malteprinzler/diner/assets/39054431/563b29c9-a1a3-463e-a959-7c0c2f66ff0b)

**Comment by malteprinzler** [comment]
Thank you very much for your interest in our work and for pointing out that bug! 
It should be fixed now. Could you please download the assets.zip file again from https://edmond.mpdl.mpg.de/dataset.xhtml?persistentId=doi:10.17617/3.NBIYQB# (same link as in the README.md) and try it again? The reason for the bug was an outdated .ckpt file. I updated them now. No changes to the code base should be necessary. Please let me know if you face any further issues. 
Best,
Malte
